version: '3'
services:
  reverse-proxy:
    depends_on:
      - redis-commander
      - mongo-express

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: on-failure
    environment:
      - REDIS_HOSTS=local:redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`redis-commander.vagrantbox.local`)"
    depends_on:
      - redis

  mongo-express:
    image: mongo-express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`mongo-express.vagrantbox.local`)"
    depends_on:
      - mongo
